-- Ensure master data tables exist and align IDs to BIGINT for upload consistency
SET @original_foreign_key_checks = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS DimSourceSystems (
    SourceSystemId BIGINT NOT NULL AUTO_INCREMENT,
    SystemCode VARCHAR(50) NOT NULL,
    SystemName VARCHAR(100) NOT NULL,
    PRIMARY KEY (SourceSystemId),
    UNIQUE KEY UX_DimSourceSystems_SystemCode (SystemCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE DimSourceSystems
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE measurement_periods
    MODIFY COLUMN period_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE DimFiscalYears
    MODIFY COLUMN FiscalYearId BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE DimLevels
    MODIFY COLUMN LevelId BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE DimEmployees
    MODIFY COLUMN EmployeeId BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE MapEmployeeAliases
    MODIFY COLUMN EmployeeAliasId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL;

ALTER TABLE MapLevelAliases
    MODIFY COLUMN LevelAliasId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN LevelId BIGINT NOT NULL;

ALTER TABLE FactPlanByLevels
    MODIFY COLUMN PlanId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN LevelId BIGINT NOT NULL;

ALTER TABLE FactEtcSnapshots
    MODIFY COLUMN EtcId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL,
    MODIFY COLUMN LevelId BIGINT NULL;

ALTER TABLE FactEngagementMargin
    MODIFY COLUMN measurement_period_id BIGINT NOT NULL;

ALTER TABLE FactDeclaredErpWeeks
    MODIFY COLUMN ErpId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL;

ALTER TABLE FactDeclaredRetainWeeks
    MODIFY COLUMN RetainId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL;

ALTER TABLE FactTimesheetCharges
    MODIFY COLUMN ChargeId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN SourceSystemId BIGINT NOT NULL,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL;

ALTER TABLE AuditEtcVsCharges
    MODIFY COLUMN AuditId BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN MeasurementPeriodId BIGINT NOT NULL,
    MODIFY COLUMN EmployeeId BIGINT NOT NULL;

SET FOREIGN_KEY_CHECKS = @original_foreign_key_checks;
