// <auto-generated />
using System;
using GRCFinancialControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRCFinancialControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012041114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PapdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClosingPeriodId");

                    b.HasIndex("EngagementId");

                    b.HasIndex("PapdId");

                    b.ToTable("ActualsEntries");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ClosingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClosingPeriods");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngagementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningMargin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPlannedHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PapdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("PapdId");

                    b.ToTable("EngagementPapds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ExceptionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Papd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Papds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AllocatedHours")
                        .HasColumnType("REAL");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("PlannedAllocations");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.ClosingPeriod", "ClosingPeriod")
                        .WithMany("ActualsEntries")
                        .HasForeignKey("ClosingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany()
                        .HasForeignKey("PapdId");

                    b.Navigation("ClosingPeriod");

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("EngagementPapds")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany()
                        .HasForeignKey("PapdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ClosingPeriod", b =>
                {
                    b.Navigation("ActualsEntries");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Navigation("EngagementPapds");
                });
#pragma warning restore 612, 618
        }
    }
}
