// <auto-generated />
using System;
using GRCFinancialControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRCFinancialControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EngagementId")
                        .HasColumnType("int");

                    b.Property<double>("Hours")
                        .HasColumnType("double");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PapdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("PapdId");

                    b.ToTable("ActualsEntries");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngagementId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("OpeningMargin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OpeningValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TotalPlannedHours")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EngagementId")
                        .HasColumnType("int");

                    b.Property<int>("PapdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("PapdId");

                    b.ToTable("EngagementPapds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ExceptionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RowData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Papd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Papds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AllocatedHours")
                        .HasColumnType("double");

                    b.Property<int>("EngagementId")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("PlannedAllocations");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany()
                        .HasForeignKey("PapdId");

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("EngagementPapds")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany()
                        .HasForeignKey("PapdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Navigation("EngagementPapds");
                });
#pragma warning restore 612, 618
        }
    }
}
