// <auto-generated />
using System;
using GRCFinancialControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRCFinancialControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PapdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClosingPeriodId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PapdId");

                    b.HasIndex("EngagementId", "Date");

                    b.ToTable("ActualsEntries");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ClosingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("ClosingPeriods");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Employee", b =>
                {
                    b.Property<string>("Gpn")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContractor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEyEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Office")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Gpn");

                    b.HasIndex("CostCenter");

                    b.HasIndex("Office");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngagementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedToCompleteHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("EtcpHours");

                    b.Property<decimal>("ExpensesEtcp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("InitialHoursBudget")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int?>("LastClosingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEtcDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MarginPctBudget")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MarginPctEtcp")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningExpenses")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OpeningValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProposedNextEtcDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("GrcProject");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnbilledRevenueDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValueEtcp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasAlternateKey("EngagementId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastClosingPeriodId");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementAdditionalSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpportunityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.ToTable("EngagementAdditionalSales");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementFiscalYearRevenueAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToDateValue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ToGoValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("EngagementFiscalYearRevenueAllocations");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementManagerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("EngagementId", "ManagerId")
                        .IsUnique();

                    b.ToTable("EngagementManagerAssignments");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PapdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PapdId");

                    b.HasIndex("EngagementId", "PapdId")
                        .IsUnique();

                    b.ToTable("EngagementPapds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementRankBudget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BudgetHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ConsumedHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Green");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("EngagementId", "FiscalYearId", "RankName")
                        .IsUnique();

                    b.ToTable("EngagementRankBudgets");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementRankBudgetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngagementCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Hours")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClosingPeriodId");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("EngagementCode", "RankCode", "FiscalYearId", "ClosingPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_History_Key");

                    b.ToTable("EngagementRankBudgetHistory", (string)null);
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ExceptionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FinancialEvolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosingPeriodId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ExpenseData")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HoursData")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MarginData")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValueData")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId", "ClosingPeriodId")
                        .IsUnique();

                    b.ToTable("FinancialEvolution", (string)null);
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AreaRevenueTarget")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("AreaSalesTarget")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsLogin")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsLogin")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Papd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsLogin")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsLogin")
                        .IsUnique();

                    b.ToTable("Papds");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocatedHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int>("ClosingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClosingPeriodId");

                    b.HasIndex("EngagementId");

                    b.ToTable("PlannedAllocations", (string)null);
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.RankMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedRank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("RankName");

                    b.Property<string>("RawRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("RankCode");

                    b.Property<string>("SpreadsheetRank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SpreadsheetRank");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedRank");

                    b.HasIndex("RawRank")
                        .IsUnique();

                    b.HasIndex("SpreadsheetRank");

                    b.ToTable("RankMappings", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BzCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId")
                        .HasDatabaseName("IX_InvoiceEmission_Item");

                    b.ToTable("InvoiceEmission", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoeResponsible")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerTicket")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDescription")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrsNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RitmNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeqNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmissionDate")
                        .HasDatabaseName("IX_InvoiceItem_EmissionDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InvoiceItem_Status");

                    b.HasIndex("PlanId", "SeqNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_InvoiceItem_PlanSeq");

                    b.ToTable("InvoiceItem", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceNotificationPreview", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ComputedDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFocalPointEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFocalPointName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngagementDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngagementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EngagementIntId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraEmails")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrsNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerEmails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerNames")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumInvoices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RitmNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeqNo")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("vw_InvoiceNotifyOnDate", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFocalPointEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFocalPointName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngagementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstEmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumInvoices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("IX_InvoicePlan_Engagement");

                    b.ToTable("InvoicePlan", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoicePlanEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_InvoicePlanEmail_Plan");

                    b.ToTable("InvoicePlanEmail", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.MailOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcCsv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SendToken")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.HasIndex("NotificationDate")
                        .HasDatabaseName("IX_MailOutbox_Notification");

                    b.HasIndex("NotificationDate", "SentAt", "SendToken")
                        .HasDatabaseName("IX_MailOutbox_Pending");

                    b.ToTable("MailOutbox", (string)null);
                });

            modelBuilder.Entity("Invoices.Core.Models.MailOutboxLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutboxId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OutboxId")
                        .HasDatabaseName("IX_MailOutboxLog_Outbox");

                    b.ToTable("MailOutboxLog", (string)null);
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ActualsEntry", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.ClosingPeriod", "ClosingPeriod")
                        .WithMany("ActualsEntries")
                        .HasForeignKey("ClosingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany()
                        .HasForeignKey("PapdId");

                    b.Navigation("ClosingPeriod");

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ClosingPeriod", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany("ClosingPeriods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Customer", "Customer")
                        .WithMany("Engagements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GRCFinancialControl.Core.Models.ClosingPeriod", "LastClosingPeriod")
                        .WithMany("Engagements")
                        .HasForeignKey("LastClosingPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("LastClosingPeriod");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementAdditionalSale", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("AdditionalSales")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementFiscalYearRevenueAllocation", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("RevenueAllocations")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementManagerAssignment", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("ManagerAssignments")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Manager", "Manager")
                        .WithMany("EngagementAssignments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementPapd", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("EngagementPapds")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Papd", "Papd")
                        .WithMany("EngagementPapds")
                        .HasForeignKey("PapdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("Papd");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementRankBudget", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("RankBudgets")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany("RankBudgets")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.EngagementRankBudgetHistory", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.ClosingPeriod", "ClosingPeriod")
                        .WithMany()
                        .HasForeignKey("ClosingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosingPeriod");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FinancialEvolution", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany("FinancialEvolutions")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.PlannedAllocation", b =>
                {
                    b.HasOne("GRCFinancialControl.Core.Models.ClosingPeriod", "ClosingPeriod")
                        .WithMany("PlannedAllocations")
                        .HasForeignKey("ClosingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRCFinancialControl.Core.Models.Engagement", "Engagement")
                        .WithMany()
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosingPeriod");

                    b.Navigation("Engagement");
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceEmission", b =>
                {
                    b.HasOne("Invoices.Core.Models.InvoiceItem", "InvoiceItem")
                        .WithMany("Emissions")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceItem", b =>
                {
                    b.HasOne("Invoices.Core.Models.InvoicePlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoicePlanEmail", b =>
                {
                    b.HasOne("Invoices.Core.Models.InvoicePlan", "Plan")
                        .WithMany("AdditionalEmails")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Invoices.Core.Models.MailOutbox", b =>
                {
                    b.HasOne("Invoices.Core.Models.InvoiceItem", "InvoiceItem")
                        .WithMany("OutboxEntries")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("Invoices.Core.Models.MailOutboxLog", b =>
                {
                    b.HasOne("Invoices.Core.Models.MailOutbox", "Outbox")
                        .WithMany("Logs")
                        .HasForeignKey("OutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.ClosingPeriod", b =>
                {
                    b.Navigation("ActualsEntries");

                    b.Navigation("Engagements");

                    b.Navigation("PlannedAllocations");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Customer", b =>
                {
                    b.Navigation("Engagements");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Engagement", b =>
                {
                    b.Navigation("AdditionalSales");

                    b.Navigation("EngagementPapds");

                    b.Navigation("FinancialEvolutions");

                    b.Navigation("ManagerAssignments");

                    b.Navigation("RankBudgets");

                    b.Navigation("RevenueAllocations");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.FiscalYear", b =>
                {
                    b.Navigation("ClosingPeriods");

                    b.Navigation("RankBudgets");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Manager", b =>
                {
                    b.Navigation("EngagementAssignments");
                });

            modelBuilder.Entity("GRCFinancialControl.Core.Models.Papd", b =>
                {
                    b.Navigation("EngagementPapds");
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoiceItem", b =>
                {
                    b.Navigation("Emissions");

                    b.Navigation("OutboxEntries");
                });

            modelBuilder.Entity("Invoices.Core.Models.InvoicePlan", b =>
                {
                    b.Navigation("AdditionalEmails");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Invoices.Core.Models.MailOutbox", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
