// <auto-generated>
//   This file provides strongly-typed access to shared resources.
// </auto-generated>

#nullable enable

namespace GRCFinancialControl.Resources.Shared;

using System.Globalization;
using System.Resources;

public static class Resources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("GRCFinancialControl.Resources.Shared.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string Shared_Common_Button_Save => ResourceManager.GetString("Shared.Common.Button.Save", resourceCulture) ?? "Shared.Common.Button.Save";

    public static string Shared_Common_Button_Cancel => ResourceManager.GetString("Shared.Common.Button.Cancel", resourceCulture) ?? "Shared.Common.Button.Cancel";
}
