database 'GRC Financial Control Dashboard'
    compatibilityLevel: 1567

model Model
    culture: en-US

    table 'Fiscal Performance'

        partition 'MySQL DirectQuery' = m
            mode: directQuery
            source = ```
                let
                    Query =
                        "SELECT\n" &
                        "    fy.Id AS FiscalYearId,\n" &
                        "    fy.Name AS FiscalYear,\n" &
                        "    fy.AreaRevenueTarget,\n" &
                        "    fy.AreaSalesTarget,\n" &
                        "    COALESCE(actuals.ActualHours, 0) AS ActualHours,\n" &
                        "    COALESCE(hoursTargets.TargetHours, 0) AS TargetHours,\n" &
                        "    COALESCE(revenueTargets.PlannedRevenue, 0) AS PlannedRevenue,\n" &
                        "    COALESCE(hoursTargets.TargetHours, 0) - COALESCE(actuals.ActualHours, 0) AS GapToTargetHours,\n" &
                        "    fy.AreaRevenueTarget - COALESCE(revenueTargets.PlannedRevenue, 0) AS GapToRevenueTarget\n" &
                        "FROM FiscalYears fy\n" &
                        "LEFT JOIN (\n" &
                        "    SELECT fyAgg.Id AS FiscalYearId, SUM(a.Hours) AS ActualHours\n" &
                        "    FROM ActualsEntries a\n" &
                        "    JOIN ClosingPeriods cp ON cp.Id = a.ClosingPeriodId\n" &
                        "    JOIN FiscalYears fyAgg ON cp.PeriodStart BETWEEN fyAgg.StartDate AND fyAgg.EndDate\n" &
                        "    GROUP BY fyAgg.Id\n" &
                        ") actuals ON actuals.FiscalYearId = fy.Id\n" &
                        "LEFT JOIN (\n" &
                        "    SELECT FiscalYearId, SUM(PlannedHours) AS TargetHours\n" &
                        "    FROM EngagementFiscalYearAllocations\n" &
                        "    GROUP BY FiscalYearId\n" &
                        ") hoursTargets ON hoursTargets.FiscalYearId = fy.Id\n" &
                        "LEFT JOIN (\n" &
                        "    SELECT FiscalYearId, SUM(PlannedValue) AS PlannedRevenue\n" &
                        "    FROM EngagementFiscalYearRevenueAllocations\n" &
                        "    GROUP BY FiscalYearId\n" &
                        ") revenueTargets ON revenueTargets.FiscalYearId = fy.Id",
                    Result =
                        MySQL.Database(
                            "{{MYSQL_SERVER}}",
                            "{{MYSQL_DATABASE}}",
                            [
                                ReturnSingleDatabase = true,
                                CreateNavigationProperties = false,
                                Query = Query
                            ]
                        )
                in
                    Result
            ```

        column FiscalYearId
            dataType: int64
            sourceColumn: FiscalYearId
            summarizeBy: none

        column 'Fiscal Year'
            dataType: string
            sourceColumn: FiscalYear
            summarizeBy: none

        column AreaRevenueTarget
            dataType: double
            sourceColumn: AreaRevenueTarget
            formatString: "#,0.00;-#,0.00;0.00"

        column AreaSalesTarget
            dataType: double
            sourceColumn: AreaSalesTarget
            formatString: "#,0.00;-#,0.00;0.00"

        column ActualHours
            dataType: double
            sourceColumn: ActualHours
            formatString: "#,0.00;-#,0.00;0.00"

        column TargetHours
            dataType: double
            sourceColumn: TargetHours
            formatString: "#,0.00;-#,0.00;0.00"

        column PlannedRevenue
            dataType: double
            sourceColumn: PlannedRevenue
            formatString: "#,0.00;-#,0.00;0.00"

        column GapToTargetHours
            dataType: double
            sourceColumn: GapToTargetHours
            formatString: "#,0.00;-#,0.00;0.00"

        column GapToRevenueTarget
            dataType: double
            sourceColumn: GapToRevenueTarget
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Actual Hours' = SUM('Fiscal Performance'[ActualHours])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Target Hours' = SUM('Fiscal Performance'[TargetHours])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Hours Gap to Target' = SUM('Fiscal Performance'[GapToTargetHours])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Hours Completion %' =
                VAR target = [Target Hours]
                RETURN IF(target = 0, BLANK(), DIVIDE([Actual Hours], target))
            formatString: "0.00%"

        measure 'Planned Revenue' = SUM('Fiscal Performance'[PlannedRevenue])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Area Revenue Target' = SUM('Fiscal Performance'[AreaRevenueTarget])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Revenue Gap to Target' = SUM('Fiscal Performance'[GapToRevenueTarget])
            formatString: "#,0.00;-#,0.00;0.00"

        measure 'Revenue Completion %' =
                VAR target = [Area Revenue Target]
                RETURN IF(target = 0, BLANK(), DIVIDE([Planned Revenue], target))
            formatString: "0.00%"
